[workspace]
resolver = "2"

members = [
    "ogcapi",
    "ogcapi-client",
    "ogcapi-drivers",
    "ogcapi-services",
    "ogcapi-types",
]
default-members = ["ogcapi"]

[workspace.package]
license = "MIT OR Apache-2.0"
repository = "https://github.com/georust/ogcapi"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.82"
geojson = "0.24.1"
log = "0.4.21"
serde = "1.0.197"
serde_json = "1.0.115"
serde_qs = "0.13.0"
thiserror = "1.0.58"
url = "2.5.0"
