[package]
name = "ogcapi-drivers"
version = "0.2.0"
description = "Driver traits and implementations"
license.workspace = true
repository.workspace = true
edition.workspace = true

include = ["/src", "/migrations"]

[features]
s3 = ["aws-config", "aws-sdk-s3"]
stac = ["ogcapi-types/stac"]
postgres = ["sqlx", "rink-core", "url"]

[dependencies]
anyhow = "1.0.82"
aws-config = { version = "1.2.0", optional = true, features = ["behavior-version-latest"] }
aws-sdk-s3 = { version = "1.23.0", optional = true, features = ["behavior-version-latest"] }
async-trait = "0.1.80"
http = "1.1.0"
rink-core = { version = "0.7.0", optional = true }
serde_json = "1.0.115"
sqlx = { version = "0.7.4", optional = true, features = ["runtime-tokio-rustls", "postgres", "json", "migrate"] }
tokio = { version = "1.37.0", features = ["full"] }
url = { version = "2.5.0", optional = true }

ogcapi-types = { path = "../ogcapi-types" }
