[package]
name = "ogcapi-drivers"
version = "0.1.3"
description = "Driver traits and implementations"
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

include = ["/src", "/migrations"]

[features]
s3 = ["aws-config", "aws-sdk-s3"]
stac = ["ogcapi-types/stac"]
postgres = ["sqlx", "rink-core", "url"]

[dependencies]
anyhow = "1.0.68"
aws-config = { version = "0.52.0", optional = true }
aws-sdk-s3 = { version = "0.22.0", optional = true }
async-trait = "0.1.60"
http = "0.2.8"
rink-core = { version = "0.6.2", optional = true }
serde_json = "1.0.91"
sqlx = { version = "0.6.2", optional = true, features = ["runtime-tokio-rustls", "postgres", "json", "migrate"] }
tokio = { version = "1.23.0", features = ["full"] }
url = { version = "2.3.1", optional = true }

ogcapi-types = { path = "../ogcapi-types" }
