[package]
name = "ogcapi"
version = "0.2.0"
description = "OGC API building blocks."
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = ["types", "client", "drivers", "services", "import"]

client = ["ogcapi-client"]
drivers = ["ogcapi-drivers"]
services = ["ogcapi-services", "ogcapi-services/full"]
types = ["ogcapi-types"]

import = ["drivers", "types", "gdal", "geo", "geojson", "osmpbfreader", "serde", "serde_json", "sqlx", "url", "wkb"]

stac = ["ogcapi-types?/stac", "ogcapi-drivers?/stac", "ogcapi-drivers?/s3", "ogcapi-services?/stac", "ogcapi-client?/stac"]

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive", "env"] }
dotenvy = "0.15.7"
gdal = { version = "0.16.0", optional = true, features = ["bindgen"] }
geo = { version = "0.28.0", optional = true }
geojson = { version = "0.24.1", optional = true, features = ["geo-types"] }
osmpbfreader = { version = "0.16.1", optional = true }
serde = { version = "1.0.197", optional = true }
serde_json = { version = "1.0.115", optional = true }
sqlx = { version = "0.7.4", optional = true, features = ["runtime-tokio-rustls", "postgres"] }
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = { version = "2.5.0", optional = true, features = ["serde"] }
wkb = { version = "0.7.1", optional = true }

ogcapi-types = { path = "../ogcapi-types", optional = true }
ogcapi-drivers = { path = "../ogcapi-drivers", optional = true }
ogcapi-services = { path = "../ogcapi-services", optional = true }
ogcapi-client = { path = "../ogcapi-client", optional = true }
