[package]
name = "ogcapi-types"
version = "0.1.0"
description = "Types as defined by various OGC API Standards."
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = []
edr = []
stac = []

[dependencies]
log = "0.4.17"
chrono = { version = "0.4.23", features = ["serde"] }
geojson = "0.24.0"
serde = "1.0.151"
serde_json = "1.0.91"
serde_repr = "0.1.10"
serde_with = { version = "2.1.0", features = ["json"] }
url = "2.3.1"
