[package]
name = "ogcapi-types"
version = "0.1.0"
description = "Types as defined by various OGC API Standards."
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = []
edr = []
stac = []

[dependencies]
log = "0.4.21"
chrono = { version = "0.4.37", features = ["serde"] }
geojson = "0.24.1"
serde = "1.0.197"
serde_json = "1.0.115"
serde_repr = "0.1.19"
serde_with = { version = "3.7.0", features = ["json"] }
url = "2.5.0"
