[package]
name = "ogcapi-client"
version = "0.2.0"
description = "Client to access OGC API Feature and STAC endpoints."
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
default = []
stac = ["ogcapi-types/stac"]

[dependencies]
log = "0.4.21"
geojson = "0.24.1"
once_cell = "1.19.0"
reqwest = { version = "0.12.3", default-features = false, features = ["json", "blocking", "rustls-tls"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
serde_qs = "0.13.0"
thiserror = "1.0.58"
url = { version = "2.5.0", features = ["serde"] }

ogcapi-types = { path = "../ogcapi-types" }
